networks:
  default:
    name: status
    driver: bridge

services:
  caddy:
    image: ghcr.io/auto-novel/shield:latest
    restart: always
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN:?}
    ports:
      - 443:443
    volumes:
      - ./data/caddy:/data
    cap_add:
      - NET_ADMIN
